sudo: required
servies: 
  - docker

before_install:
  - docker build -t hemanthpeela09/docker-react -f Dockerfile.dev .

script:
  - docker run hemanthpeela09/docker-react npm run test -- --coverage
